version: "3"
services:
  roscore:
    container_name: benchbot_roscore
    image: benchbot/simulator:devel
    command: /bin/bash -c "source /home/benchbot/ros_ws/devel/setup.bash && roscore"
  simulator:
    container_name: benchbot_simulator
    image: benchbot/simulator:devel
    command: /bin/bash -c 'source /home/benchbot/ros_ws/devel/setup.bash &&
                           ROS_MASTER_URI=http://benchbot_roscore:11311 && 
                           ROS_HOSTNAME=benchbot_simulator &&
                           cd benchbot_simulator &&
                           ./build run //apps/benchbot_simulator'
  # This won't work as there appears to be no way to pass '--gpus all' through a compose file..........
  # isaac_sim:
  #   container_name: benchbot_isaac_sim
  #   image: benchbot/simulator:devel
  #   environment:
  #     DISPLAY:
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #   command: /bin/bash -c 'cd isaac_sim &&
  #                         ./Engine/Binaries/Linux/UE4Editor \
  #                         IsaacSimProject Hospital vulkan \
  #                         -isaac_sim_config_json="/home/ben/opt/isaac_sdk/apps/carter/carter_sim/bridge_config/carter_full.json" \
  #                         -game -windowed -ResX=1024 -RexY=720'
  debug:
    container_name: benchbot_debug
    image: benchbot/simulator:devel
    environment:
      DISPLAY:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: /bin/bash 
    stdin_open: true
